### ISSUE TITLE
Azi_Drive: Thrust clipping

### ISSUE THREAD

**Issue by jpanikulam** [uf-mil/PropaGator#10]
Azi drive is auto-clipping incoming wrench commands to avoid impossible commands. 

When the vehicle is commanded with too large a wrench, azi-drive does not converge, and the existing azi-drive codebase does not handle this well.
This is half-solved, in the sense that the clipping will prevent a convergence problem in 99% of cases (Exceptions in the angle-ranging problem).

Lines causing this:
https://github.com/uf-mil/PropaGator/blob/master/azi_drive/nodes/azi_drive_node.py#L124

**Comment by jpanikulam** [comment]
@zachgoins 

I won't have time to fix this until June.

Possible fixes:
1. Find the maximum wrench (at thruster saturation) for current configuration and set those to the clips

    min_T = B * [-100, -100].T
    max_T = B * [100,  100].T

2. Design a smarter controller/planner that commands in Newtons, N*m and knows to clip at realistic values.

**Comment by fnivek** [comment]
Is this fixed? Would it be better to scale all values equally to maintain the direction of the force vector? Clipping would change the direction of the force vector which is bad for the controller.
