### ISSUE TITLE
WP_controller: Make orientation a ROS service

### ISSUE THREAD

**Issue by zachgoins** [uf-mil/PropaGator#26]
Create a ROS service to change how much the orientation matters to us at a given time.
Drop orientation weight a bit when making large waypoint changes (much faster than worrying about orientation while moving) and make orientation precise when we need it to be. May overcome a lot of issues

**Comment by fnivek** [comment]
The way point msg type has an orientation tolerance. Maybe you could use that instead?

**Comment by fnivek** [comment]
Outdated
