### ISSUE TITLE
Fixing boat.float() function?

### ISSUE THREAD

**Issue by rleyva** [uf-mil/PropaGator#31]
Hey guys, I need the float command in the boat class updated to allow me to stop the boat while carrying out the hydrophone mission. Running the thrusters causes too much noise when I'm looking for the pinger.

**Comment by LucasBA** [comment]
I believe if when you write your mission you call the float function then call the hydrohone function then yield on both functions it will run them simultaneously

**Comment by rleyva** [comment]
Fixed. boat.float() has now been converted to two function, float_on and float_off.
